name: ad
on: workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo flag
        run: echo "${{ github.ref_type }}"
      - name: set tag to IMAGE_TAG
        id: get_tag
        run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: set sha to IMAGE_TAG
        if: steps.get_tag.conclusion == 'skipped'
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
      - name: echo IMAGE_TAG
        run: echo "${{ env.IMAGE_TAG }}"
