name: changes
on:
  push:
    branches:
      - '*'
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo name
        run: |
          echo "${{ github.event_name }}"
          echo "${{ github.ref_name }}"
  ad:
    needs: changes
    uses: ./.github/workflows/ad.yml
    secrets: inherit